### ISSUE TITLE
Expected ';' after top level declarator

### ISSUE THREAD

**Issue by jollyrogersfabric** [TwilioDevEd/client-quickstart-objc#1]
I have tried to compile the objc project with Xcode 6.1 and IOS 8 but get the error: Expected ';' after top level declarator.
I have followed the instructions how to set up the project with cocoapods. https://www.twilio.com/docs/quickstart/client/ios#download-the-ios-app

Do I need Xcode 7 and IOS9 or what can the problem be?

**Comment by jefflinwood** [comment]
Hi,

I haven't tried out the project with XCode 6.1 - does XCode tell you which line is the problem?

Thanks!

**Comment by jollyrogersfabric** [comment]
Yes,

Here is more details:

CompileC /Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/Objects-normal/x86_64/DialViewController.o ObjectiveCTwilioClientQuickstart/DialViewController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DCOCOAPODS=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=8.2 -iquote /Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/ObjectiveCTwilioClientQuickstart-generated-files.hmap -I/Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/ObjectiveCTwilioClientQuickstart-own-target-headers.hmap -I/Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/ObjectiveCTwilioClientQuickstart-all-target-headers.hmap -iquote /Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/ObjectiveCTwilioClientQuickstart-project-headers.hmap -I/Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public -I/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient -I/Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/DerivedSources/x86_64 -I/Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/DerivedSources -F/Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Products/Debug-iphonesimulator -isystem /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public -isystem /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient -isystem /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public -isystem /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient -MMD -MT dependencies -MF /Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/Objects-normal/x86_64/DialViewController.d --serialize-diagnostics /Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/Objects-normal/x86_64/DialViewController.dia -c /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/ObjectiveCTwilioClientQuickstart/DialViewController.m -o /Users/MyTwilioComp/Library/Developer/Xcode/DerivedData/ObjectiveCTwilioClientQuickstart-anvxgkgdcxcqlhbaxykdwyfaacsf/Build/Intermediates/ObjectiveCTwilioClientQuickstart.build/Debug-iphonesimulator/ObjectiveCTwilioClientQuickstart.build/Objects-normal/x86_64/DialViewController.o

In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/ObjectiveCTwilioClientQuickstart/DialViewController.m:9:
In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/ObjectiveCTwilioClientQuickstart/DialViewController.h:11:
In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TwilioClient.h:8:
In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:10:
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnectionDelegate.h:33:21: error: expected a type
- (void)connection:(nonnull TCConnection *)connection didFailWithError:(nullable NSError *)error;
                    ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnectionDelegate.h:33:73: error: expected a type
- (void)connection:(nonnull TCConnection *)connection didFailWithError:(nullable NSError *)error;
                                                                        ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnectionDelegate.h:47:39: error: expected a type
- (void)connectionDidStartConnecting:(nonnull TCConnection *)connection;
                                      ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnectionDelegate.h:59:31: error: expected a type
- (void)connectionDidConnect:(nonnull TCConnection *)connection;
                              ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnectionDelegate.h:71:34: error: expected a type
- (void)connectionDidDisconnect:(nonnull TCConnection *)connection;
                                 ^
In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/ObjectiveCTwilioClientQuickstart/DialViewController.m:9:
In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/ObjectiveCTwilioClientQuickstart/DialViewController.h:11:
In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TwilioClient.h:8:
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:43:28: error: expected ';' after top level declarator
extern NSString * __nonnull const TCConnectionIncomingParameterFromKey;
                           ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:46:28: error: expected ';' after top level declarator
extern NSString * __nonnull const TCConnectionIncomingParameterToKey;
                           ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:49:28: error: expected ';' after top level declarator
extern NSString * __nonnull const TCConnectionIncomingParameterAccountSIDKey;
                           ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:52:28: error: expected ';' after top level declarator
extern NSString * __nonnull const TCConnectionIncomingParameterAPIVersionKey;
                           ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:55:28: error: expected ';' after top level declarator
extern NSString * __nonnull const TCConnectionIncomingParameterCallSIDKey DEPRECATED_ATTRIBUTE;
                           ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:55:35: error: unknown type name 'TCConnectionIncomingParameterCallSIDKey'
extern NSString * __nonnull const TCConnectionIncomingParameterCallSIDKey DEPRECATED_ATTRIBUTE;
                                  ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:55:75: error: expected identifier or '('
extern NSString * __nonnull const TCConnectionIncomingParameterCallSIDKey DEPRECATED_ATTRIBUTE;
                                                                          ^
In module 'UIKit' imported from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/ObjectiveCTwilioClientQuickstart/DialViewController.h:9:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKitDefines.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk/usr/include/AvailabilityMacros.h:162:45: note: expanded from macro 'DEPRECATED_ATTRIBUTE'
        #define DEPRECATED_ATTRIBUTE        __attribute__((deprecated))
                                            ^
In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/ObjectiveCTwilioClientQuickstart/DialViewController.m:9:
In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/ObjectiveCTwilioClientQuickstart/DialViewController.h:11:
In file included from /Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TwilioClient.h:8:
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:65:28: error: expected ';' after top level declarator
extern NSString * __nonnull const TCConnectionParameterCallSIDKey;
                           ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:102:39: error: unknown property attribute 'nullable'
@property (weak, nonatomic, readonly, nullable) NSDictionary <NSString *, NSString *> *parameters;
                                      ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:102:72: error: expected '>'
@property (weak, nonatomic, readonly, nullable) NSDictionary <NSString *, NSString *> *parameters;
                                                                       ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:102:73: error: expected member name or ';' after declaration specifiers
@property (weak, nonatomic, readonly, nullable) NSDictionary <NSString *, NSString *> *parameters;
                                                ~~~~~~~~~~~~            ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:102:1: error: property requires fields to be named
@property (weak, nonatomic, readonly, nullable) NSDictionary <NSString *, NSString *> *parameters;
^                                               ~~~~~~~~~~~~~~~~~~~~~~~~
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:102:75: error: interface type cannot be statically allocated
@property (weak, nonatomic, readonly, nullable) NSDictionary <NSString *, NSString *> *parameters;
                                                                          ^
/Users/MyTwilioComp/Documents/MyTwilioProj/client-quickstart-objc-master/Pods/Headers/Public/TwilioClient/TCConnection.h:102:83: error: expected ';' at end of declaration list
@property (weak, nonatomic, readonly, nullable) NSDictionary <NSString *, NSString *> *parameters;
                                                                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by jollyrogersfabric** [comment]
More details: XCode Version 6.2 (6C131e).
Destination: iPhone 6 Plus SDK Simulator iOS 8.2
OSX 10.9.5

**Comment by jollyrogersfabric** [comment]
Upgraded OSX to El Capitan, tested with XCode v 6.4 and then XCode 7v, same error. Upgraded XCode to v8 everything compiles. Closing!
